{{
 config(
 materialized = 'table',
 )
}}


WITH RATING AS (
  SELECT DISTINCT
    POTENTIAL_RATING,
    PERFORMANCE_RATING
  FROM {{ref("combined_data")}}
  WHERE PERFORMANCE_RATING IS NOT NULL AND POTENTIAL_RATING IS NOT NULL
)

SELECT
  ROW_NUMBER() OVER (ORDER BY POTENTIAL_RATING, PERFORMANCE_RATING) AS RATING_KEY,
  *
FROM RATING

