{{
 config(
 materialized = 'table',
 )
}}

WITH l AS (SELECT distinct COURSE,
COURSE_NAME,
COURSE_TYPE,
COURSE_VERSION,
LANGUAGE,
VENDOR

 FROM 
{{ref("combined_data")}}
)

SELECT ROW_NUMBER() OVER (ORDER BY COURSE,COURSE_NAME,COURSE_TYPE,COURSE_VERSION,VENDOR) AS COURSE_KEY,* FROM l 
ORDER BY COURSE,
COURSE_NAME,
COURSE_TYPE,
COURSE_VERSION,
LANGUAGE,
VENDOR