{{
 config(
 materialized = 'table',
 )
}}


  SELECT DISTINCT md5(POTENTIAL_RATING || PERFORMANCE_RATING) AS RATING_KEY,
    POTENTIAL_RATING,
    PERFORMANCE_RATING
  FROM {{ref("active_employees_cleaned")}}
  WHERE PERFORMANCE_RATING IS NOT NULL AND POTENTIAL_RATING IS NOT NULL



