{{
  config(materialized='incremental',
    unique_key='ASSIGNMENT_KEY',
    incremental_strategy='delete+insert')
}}


  SELECT
   distinct md5(HOURLY_SALARY || ASSIGNMENT_STATUS || ASSIGNMENT_EMPLOYMENT_CATEGORY || ASSIGNMENT_NAME || 
    ASSIGNMENT_CURRENT_CHG_ACTION || ASSIGNMENT_CURRENT_CHG_REASON || ASSIGNMENT_CURRENT_EFFECTIVE_DATE || GRADE_NAME) AS ASSIGNMENT_KEY,
                  HOURLY_SALARY, ASSIGNMENT_STATUS, ASSIGNMENT_EMPLOYMENT_CATEGORY, ASSIGNMENT_NAME,
                 ASSIGNMENT_CURRENT_CHG_ACTION, ASSIGNMENT_CURRENT_CHG_REASON, ASSIGNMENT_CURRENT_EFFECTIVE_DATE,
                  GRADE_NAME
  FROM {{ref("combined_data")}}

