{{
 config(
 materialized = 'table',
 )
}}


WITH l AS (
  SELECT distinct HOURLY_SALARY, ASSIGNMENT_STATUS, ASSIGNMENT_EMPLOYMENT_CATEGORY, ASSIGNMENT_NAME,
                 ASSIGNMENT_CURRENT_CHG_ACTION, ASSIGNMENT_CURRENT_CHG_REASON, ASSIGNMENT_CURRENT_EFFECTIVE_DATE,
                  GRADE_NAME
  FROM {{ref("combined_data")}}
)

  SELECT *, ROW_NUMBER() OVER (ORDER BY HOURLY_SALARY, ASSIGNMENT_STATUS, ASSIGNMENT_EMPLOYMENT_CATEGORY, ASSIGNMENT_NAME,
                 ASSIGNMENT_CURRENT_CHG_ACTION, ASSIGNMENT_CURRENT_CHG_REASON, ASSIGNMENT_CURRENT_EFFECTIVE_DATE,
                  GRADE_NAME ) AS ASSIGNMENT_KEY from l

