with active_employees as (
      select *,  ROW_NUMBER() OVER (PARTITION BY ftv_id ORDER BY Assignment_Current_Effective_Date DESC) AS RowNum
      from {{source('JAY','db_active_employees')}} where PERSON_TYPE = 'Employee'
)
    select FTV_ID,
PERSON_TYPE,
WORKER_TYPE,
DATE_OF_BIRTH,
AGE,
ASSIGNMENT_STATUS,
ASSIGNMENT_CURRENT_EFFECTIVE_DATE,
ASSIGNMENT_CURRENT_CHG_ACTION,
ASSIGNMENT_CURRENT_CHG_REASON,
ASSIGNMENT_EMPLOYMENT_CATEGORY,
SEGMENT,
OPCO,
SUB_OPCO,
LEGAL_ENTITY_NAME,
BUSINESS_UNIT_NAME,
DEPARTMENT_NAME,
ASSIGNMENT_NAME,
JOB_TITLE,
JOB_FUNCTION,
JOB_FAMILY,
EEO_CATEGORY,
CAREER_BAND,
CAREER_LEVEL,
GRADE_NAME,
HOURLY_SALARY,
FTE,
ORIGINAL_HIRE_DATE,
LATEST_HIRE_DATE,
ADJUSTED_SERVICE_DATE,
LENGTH_OF_SERVICE,
L1_LEADER,
MANAGER_FTV_ID,
WORK_REGION,
WORK_COUNTRY,
WORK_STATE,
WORK_CITY,
WORK_LOCATION,
HEADCOUNT,
SALARY,
CURRENCY_CODE,
PERFORMANCE_RATING,
POTENTIAL_RATING
 from active_employees WHERE
  RowNum = 1


  